#!/usr/bin/env bash

testWarnOldDjango() {
  compile "old-django"
  assertCaptured "Your Django version is nearing the end of its community support."
  assertCapturedSuccess
}

testDontWarnOldDjango() {
  compile "not-old-django"
  assertNotCaptured "Your Django version is nearing the end of its community support."
  assertCapturedSuccess
}

pushd $(dirname 0) >/dev/null
popd >/dev/null

source $(pwd)/test/utils
source $(pwd)/test/shunit2
