version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "ruby"
      - "skip changelog"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github actions"
      - "skip changelog"
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "python"
