version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "ruby"
      - "skip changelog"
    groups:
      ruby-dependencies:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github actions"
      - "skip changelog"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      # We're not updating to setuptools v71+ due to its new approach to vendored dependencies:
      # https://github.com/heroku/heroku-buildpack-python/pull/1630#issuecomment-2324236653
      - dependency-name: "setuptools"
    labels:
      - "dependencies"
      - "python"
