require:
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/Focus:
  # Disable auto-correct otherwise format-on-save will remove the annotation
  # whilst developing locally.
  AutoCorrect: false

RSpec/MultipleExpectations:
  Enabled: false
