[buildpack]
name = "Python"

[publish.Ignore]
files = [
  ".git2gus/",
  ".github/",
  "builds/",
  "spec/",
  ".dockerignore",
  ".gitignore",
  ".rubocop.yml",
  ".travis.yml",
  "Gemfile",
  "Gemfile.lock",
  "hatchet.json",
  "hatchet.lock",
  "Makefile",
  "requirements.txt",
]
