#!/usr/bin/env bash
# Build Path: /app/.heroku/python/
# Build Deps: libraries/sqlite

# download_python(PYTHON_VERSION)
# Example usage: download_python "2.7.7"
download_python()
{
    PYTHON_VERSION=$1

    if [ -z $PYTHON_VERSION ]
    then
        $PYTHON_VERSION="2.7.7"
    fi

    echo "Building Python $PYTHON_VERSION..."
    SOURCE_TARBALL="http://python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz"
    curl -L $SOURCE_TARBALL | tar xz
    mv Python-$PYTHON_VERSION src
}
