#!/usr/bin/env bash

set -euo pipefail

# This is set by bob-builder from the "Build Path" comment line in the
# build formula script that sourced this one.
OUT_PREFIX=$1
# The filename of the script that sourced this one (e.g. `python-3.10.0`).
FORMULA_FILENAME=$(basename "${0}")
# The version component (e.g. `3.10.0`).
VERSION=$(echo "${FORMULA_FILENAME}" | cut --delimiter '-' --fields 2)

echo "Building Python ${VERSION}..."

# See: https://www.python.org/downloads/ -> "OpenPGP Public Keys"
case "${VERSION}" in
  3.10.*)
    # https://keybase.io/pablogsal/
    GPG_KEY_FINGERPRINT='A035C8C19219BA821ECEA86B64E628F8D684696D'
    ;;
  3.[8-9].*)
    # https://keybase.io/ambv/
    GPG_KEY_FINGERPRINT='E3FF2839C048B25C084DEBE9B26995E310250568'
    ;;
  3.7.*)
    # https://keybase.io/nad/
    GPG_KEY_FINGERPRINT='0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D'
    ;;
  *)
    echo "Unsupported Python version!" >&2
    exit 1
    ;;
esac

SOURCE_URL="https://www.python.org/ftp/python/${VERSION}/Python-${VERSION}.tgz"
SIGNATURE_URL="${SOURCE_URL}.asc"

set -o xtrace

curl --fail --retry 3 --connect-timeout 5 --max-time 60 -o python.tgz "${SOURCE_URL}"
curl --fail --retry 3 --connect-timeout 5 --max-time 60 -o python.tgz.asc "${SIGNATURE_URL}"

gpg --batch --recv-keys "${GPG_KEY_FINGERPRINT}"
gpg --batch --verify python.tgz.asc python.tgz

mkdir src
tar --extract --file python.tgz --strip-components=1 --directory src/
cd src

# Aim to keep this roughly consistent with the options used in the Python Docker images,
# for maximum compatibility / most battle-tested build configuration:
# https://github.com/docker-library/python
CONFIGURE_OPTS=(
  # Support loadable extensions in the `_sqlite` extension module.
  "--enable-loadable-sqlite-extensions"
  # Make autoconf's configure option validation more strict.
  "--enable-option-checking=fatal"
  # Install Python into `/app/.heroku/python` rather than the default of `/usr/local`.
  "--prefix=${OUT_PREFIX}"
  # Skip running `ensurepip` as part of install, since the buildpack installs a curated
  # version of pip itself (which ensures it's consistent across Python patch releases).
  "--with-ensurepip=no"
  # Build the `pyexpat` module using the `expat` library in the stack image (which will
  # automatically receive security updates), rather than CPython's vendored version.
  "--with-system-expat"
)

if [[ "${VERSION}" != 3.7.* ]]; then
  CONFIGURE_OPTS+=(
    # Python 3.7 and older run the whole test suite for PGO, which takes
    # much too long. Whilst this can be overridden via `PROFILE_TASK`, we
    # prefer to change as few of the upstream build options as possible.
    # As such, PGO is only enabled for Python 3.8+.
    "--enable-optimizations"
  )
fi

./configure "${CONFIGURE_OPTS[@]}"

make -j "$(nproc)"
make install

# Remove unneeded test directories, similar to the official Docker Python images:
# https://github.com/docker-library/python
# TODO: Explore using --disable-test-modules once the PGO fix is in a released Python version:
# https://bugs.python.org/issue45668
find "${OUT_PREFIX}" -depth -type d -a \( -name 'test' -o -name 'tests' -o -name 'idle_test' \) -exec rm -rf '{}' +

# Support using Python 3 via the version-less `python` command, for parity with virtualenvs,
# the Python Docker images and to also ensure buildpack Python shadows any installed system
# Python, should that provide a version-less alias too.
# This symlink must be relative, to ensure that the Python install remains relocatable.
ln -srvT "${OUT_PREFIX}/bin/python3" "${OUT_PREFIX}/bin/python"
