#!/bin/bash

# To run, from ~/workspace/buildpacks/cf-buildpack-python
#
#   bin/test_package

# ==================================== Mocks ====================================
# The mocks are not subshell safe.  They work by defining a global bash function that takes precedence over the UNIX
# tools like curl and zip
function curl() {
    args="$@";
    ARGUMENTS_CALLED_WITH_FOR_CURL=("${ARGUMENTS_CALLED_WITH_FOR_CURL[@]}" "$args");
    return 0;
}

function zip() {
    args="$@";
    ARGUMENTS_CALLED_WITH_FOR_ZIP=("${ARGUMENTS_CALLED_WITH_FOR_ZIP[@]}" "$args");
    return 0;
}

# Reset mocks
setUp() {
    ARGUMENTS_CALLED_WITH_FOR_CURL=()
    ARGUMENTS_CALLED_WITH_FOR_ZIP=()
}

# ==================================== Tests ====================================
testDependenciesAreDownloadedInOfflineMode() {
    source $BIN/package offline

    assertEquals 'curl should download files with the url in the saved filename'     \
                   '-o ./dependencies/http___lang-python.s3.amazonaws.com_runtimes_python-2.7.0.tar.gz http://lang-python.s3.amazonaws.com/runtimes/python-2.7.0.tar.gz -L' \
                   "${ARGUMENTS_CALLED_WITH_FOR_CURL[0]}"

    assertEquals 'curl downloads 13 dependencies' "13" "${#ARGUMENTS_CALLED_WITH_FOR_CURL[@]}"
}

testDependenciesAreNotDownloadedInOnlineMode() {
    source $BIN/package online

    assertEquals 'curl downloads 0 dependencies' "0" "${#ARGUMENTS_CALLED_WITH_FOR_CURL[@]}"
}

testZipForBuildpackIsCreated() {
    source $BIN/package online

    assertEquals 'Buildpack is zipped' "1" "${#ARGUMENTS_CALLED_WITH_FOR_ZIP[@]}"
}

testOnlineZipIsCreatedWithCorrectName() {
    source $BIN/package online
    first_call=${ARGUMENTS_CALLED_WITH_FOR_ZIP[0]}
    assertTrue "online zip has version number and no mode" $(contains "$first_call" "python_buildpack-v1.0.0.zip")
}

testOfflineZipIsCreatedWithCorrectName() {
    source $BIN/package offline
    first_call=${ARGUMENTS_CALLED_WITH_FOR_ZIP[0]}
    assertTrue "offline zip has version number and mode" $(contains "$first_call" "python_buildpack-offline-v1.0.0.zip")
}

testExcludeFilesFromTheBuildpack() {
    source $BIN/package online

    arguments=$ARGUMENTS_CALLED_WITH_FOR_ZIP[@]

    assertTrue "zip excludes .git"       $(contains "$arguments" " --exclude=*.git/*")
    assertTrue "zip excludes .gitignore" $(contains "$arguments" " --exclude=*.gitignore*")
    assertTrue "zip excludes cf_spec"    $(contains "$arguments" " --exclude=*cf_spec/*")
    assertTrue "zip excludes log"        $(contains "$arguments" " --exclude=*log/*")
    assertTrue "zip excludes test"       $(contains "$arguments" " --exclude=*test/*")
}

# ==================================== Utilities ====================================
function contains() {
    string=$1
    substring=$2

    if [[ $string == *"${substring}"* ]]
    then
        echo '0'
    else
        echo '1'
    fi
}

BASE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BIN=$BASE/../bin
source $BASE/../vendor/shunit2
