#!/usr/bin/env bash
# Build Path: /app/.heroku/python/

OUT_PREFIX=$1

echo "Building autoconf..."


SOURCE_TARBALL='https://ftp.gnu.org/gnu/autoconf/autoconf-2.68.tar.gz'
curl -L $SOURCE_TARBALL | tar xz

cd autoconf-2.68
./configure --prefix=$OUT_PREFIX
make
make install