#!/usr/bin/env bash
# Build Path: /app/.heroku/python/

OUT_PREFIX=$1

# Use new path, containing autoconf.
export PATH="/app/.heroku/python/bin/:$PATH"
hash -r


echo "Building libffi..."

SOURCE_TARBALL='https://cl.ly/2s1t1u3v0N0I/download/libffi-3.1.tar'

curl -L $SOURCE_TARBALL | tar x

cd libffi-3.1
./configure --prefix=$OUT_PREFIX --disable-static &&
make
make install

# Cleanup
cd ..
