#!/usr/bin/env bash
# Build Path: /app/.heroku/python/

OUT_PREFIX=$1

echo "Building SQLite..."


SOURCE_TARBALL='https://www.sqlite.org/sqlite-autoconf-3070900.tar.gz'

curl $SOURCE_TARBALL | tar xz
# jx
mv sqlite-autoconf-3070900 sqlite

cd sqlite
./configure --prefix=$OUT_PREFIX
make
make install

# Cleanup
cd ..
rm -fr sqlite
