#!/usr/bin/env bash
# Build Path: /app/.heroku/python/

OUT_PREFIX=$1

echo "Building SQLite…"


SOURCE_TARBALL='https://www.sqlite.org/2018/sqlite-autoconf-3240000.tar.gz'

curl $SOURCE_TARBALL | tar xz
# jx
mv sqlite-autoconf-3240000 sqlite

cd sqlite
./configure --prefix=$OUT_PREFIX
make
make install

# Cleanup
cd ..
rm -fr sqlite
